create database customer_behavior;
use  customer_behavior;

select * from  mytable limit 20;


#Ques1- what is the total revenue generated by male vs female customers

select gender , sum(purchase_amount) as total_revenue
from mytable
group by gender;



#Ques2- which customers used a discount but still spend more than the average purchase amount

select customer_id , purchase_amount
from mytable
where discount_applied= "Yes" and purchase_amount > (
select avg(purchase_amount)
from mytable 
);



#Ques3- which are the top 5 products with the highest average review rating?

select item_purchased , avg(review_rating)as average_review_rating
from mytable 
group by item_purchased
order by average_review_rating desc
limit 5;



#Ques4- compare the average purchase amounts between standard and express shipping.

select shipping_type , avg(purchase_amount) as average_purchase_amount
from mytable
where shipping_type in ('Express', 'Standard')
group by shipping_type;



# Ques5- do subscribed customers spend more ? compare average spent and total revenue btween subscribers and non-subscribers

select subscription_status, count(customer_id) as total_customers , avg(purchase_amount) as average_purchased_amount , sum(purchase_amount) as total_revenue
from mytable
group by subscription_status;
#ans- as i checked the answer is no , non-sub are spending more than subs one.



#Ques6- which 5 products have the highest percentage of purchase with discount applied?

select item_purchased,
100*sum(case when discount_applied='Yes' then 1 else 0 end ) / count(customer_id)  as discount_rate
from mytable 
group by item_purchased
order by discount_rate desc
limit 5;



#Ques7- segment customers into new , returning , and loyal based on their total number of previous purchase and show the count of each segment

WITH customer_type AS (
   SELECT 
      customer_id,
      CASE
         WHEN previous_purchases = 1 THEN 'New'
         WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
         ELSE 'Loyal'
      END AS customer_type
   FROM mytable
)

SELECT 
   customer_type,
   COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_type;



#Ques8-top 3 most purchased products with each category

WITH product_rank AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM mytable
    GROUP BY category, item_purchased
)

SELECT 
    category,
    item_purchased,
    total_orders
FROM product_rank
WHERE rn <= 3
ORDER BY category, total_orders DESC;



#Ques9- are customers who are repeat buyers (more than 5 prev purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status;



#Ques10- what is the revenue contribution of each age group 

select age_group , sum(purchase_amount) as revenue_contribution
from mytable
group by age_group
order by revenue_contribution desc;


